name: Merge stable_develop tag into target branch

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: "Target branch to merge stable_develop tag into"
        required: true
        type: string

jobs:
  merge:
    runs-on: ubuntu-24.04 
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1 # at first we're just getting the latest commit
          ref: ${{ github.event.inputs.target_branch }}
          fetch-tags: false   # don't pull every tag to speed up this step      

      - name: Set up Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Ensure full history (only if shallow)
        run: |
          branch_name="${{ github.event.inputs.target_branch }}"
          if [ -f .git/shallow ]; then
            echo "Repository is shallow. Fetching full history for $branch_name..."
            git fetch --unshallow origin "$branch_name"
          else
            echo "Repository already has full history, skipping unshallow."
          fi

      - name: fetch stable_develop tags
        run: |
          if git ls-remote --tags origin | grep -q "refs/tags/stable_develop$"; then
            echo "Fetching develop and the stable_develop tag..."
            git fetch origin refs/tags/stable_develop:refs/tags/stable_develop
          else
            echo "::error::stable_develop tag does not exist on origin."
            exit 1
          fi

      - name: Detect merge conflicts (dry run)
        run: |
          branch_name="${{ github.event.inputs.target_branch }}"
          echo "Checking for merge conflicts between stable_develop tag and $branch_name..."

          base=$(git merge-base $branch_name stable_develop)
          if ! git merge-tree $base $branch_name stable_develop | grep -q '<<<<<<<'; then
            echo "No merge conflicts detected."
          else
            echo "::error::Merge conflict detected between stable_develop tag and $branch_name."
            exit 1
          fi

      - name: Merge stable_develop tag into target branch
        run: |
          set -e
          branch_name="${{ github.event.inputs.target_branch }}"

          echo "Merging stable_develop tag into $branch_name..."
          git merge stable_develop -m "Merge stable_develop tag"

          echo "Pushing changes..."
          git push origin "$branch_name"